config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  post 'login'  => 'placeholder#login',   :as => 'login'
  get  'login'  => 'placeholder#landing', :as => 'landing'
  get 'generate_orgs' => 'placeholder#generate_orgs', :as => 'finish_quiz'

  match '/auth/:provider/callback', to: "sessions#create", via: [:get, :post]
  get 'signin' => "sessions#signin", :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get 'auth/failure' => 'sessions#failure'

  root 'placeholder#home'
  resources :quizzes
  resources :response
  get 'quiz', to: 'quizzes#quiz', as: :take_quiz

  get 'profile/:id'=> 'profile#show', :as => 'show_profile'
  get 'profile/:id/edit' => 'profile#edit', :as => 'edit_profile'
  post 'profile/:id' => 'profile#update', :as => 'update_profile'
  
  get 'interests' => 'interests#index', :as => 'interests'
  post 'interests/upload' => 'interests#upload', :as => 'upload_interests'
end

app/models/question.rb
class Question < ApplicationRecord
  serialize :options, Hash
  serialize :next_question, Hash
  def question_queue_content(selected_options)
    question_queue = []
    content = []
    selected_options.each do |option|
      id = self.next_question[option]
      # content << self.options[option]
      content = content.concat self.options[option]
      if id
        question_queue << id
      end
    end
    return {
      :question_queue => question_queue, 
      :content => content, 
      :question_type => self.question_type,
    }
  end
end

app/views/questions/_form.html.erb
<%= form_tag(response_index_path, method: 'post', class: 'form-check', remote: true, id: 'response-form') do %>
  <div class="modal-body text-left" id='question-container'>
    <% if alert %>
      <!-- Alert if problem saving response. -->
      <p class="alert alert-warning alert-dismissible fade show">
        <%= alert %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </p>
    <% end %>
    <% if @question.nil? %>
      <h5 class='card-title'>You finished the quiz!</h5>
    <% else %>
      <h5 class='card-title'><%= @question.title %></h5>
      <div id='options-container'>
        <% @question.options.each do |option_title, _| %>
          <label><%= check_box_tag("selected_options[]", option_title) %> <%= option_title %></label>
          <br>
        <% end %>
      </div>
      <%= hidden_field_tag(:question_id, @question.id) %>
      <%= hidden_field_tag(:quiz_id, @quiz.id) %>
    <% end %>
  </div>
  <div class="modal-footer">
    <% if @question.nil? %>
      <%= link_to "See Orgs", finish_quiz_path(:quiz_id => @quiz.id), :id => 'finish-quiz', :class => "btn btn-finish-quiz", :remote => true, "data-dismiss" => "modal" %>
    <% else %>
      <%= submit_tag('Next Question', class: 'btn btn-warning', id: 'submit-response-btn') %>
    <% end%>
  </div>
<% end %>