config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  post 'login'  => 'placeholder#login',   :as => 'login'
  get  'login'  => 'placeholder#landing', :as => 'landing'
  get 'generate_orgs' => 'placeholder#generate_orgs', :as => 'finish_quiz'

  match '/auth/:provider/callback', to: "sessions#create", via: [:get, :post]
  get 'signin' => "sessions#signin", :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get 'auth/failure' => 'sessions#failure'

  root 'placeholder#home'
  resources :quizzes
  resources :response
  get 'quiz', to: 'quizzes#quiz', as: :take_quiz

  get 'profile/:id'=> 'profile#show', :as => 'show_profile'
  get 'profile/:id/edit' => 'profile#edit', :as => 'edit_profile'
  post 'profile/:id' => 'profile#update', :as => 'update_profile'
  
  get 'interests' => 'interests#index', :as => 'interests'
  post 'interests/upload' => 'interests#upload', :as => 'upload_interests'
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController

  # GET /quizzes/new
  def new
    @quiz = Quiz.new
  end

  def quiz
    # Defaults to quiz 1, but should change once we implement user
    # should change to: Quiz.where(user_id: @user.id)
    @quiz = Quiz.find(1)
    redirect_to quizzes_path unless @quiz
    @question = Question.find(@quiz.current_question)
    @response = Response.new
  end

  # POST /quizzes
  # POST /quizzes.json
  def create
    @quiz = Quiz.new(current_question: 1)
    @question = Question.find(@quiz.current_question)
    @response = Response.new
    respond_to do |format|
      if @quiz.save
        cookies[:finished_quiz] = false
        format.js
      else
        format.js { flash[:alert] = 'There was a problem creating quiz.' }
      end
    end
  end

end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/views/quizzes/_form.html.erb
<!-- Modal -->
<div class="modal fade" id="quiz-modal" tabindex="-1" role="dialog" aria-labelledby="quiz-modalTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div id='modal-content' class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Quiz</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div id='response-form-container'>
      </div>
    </div>
  </div>
</div>

<%= form_tag(quizzes_path, method: "post", remote: true) do %>
  <div class="text-center">
    <%= submit_tag('Start', id: 'start-quiz-btn', class: 'btn start-quiz-btn btn-outline-warning', 'data-toggle': 'modal', 'data-target': '#quiz-modal', 'data-backdrop': 'static', 'data-keyboard': 'false', data: { disable_with: false }) %>
  </div>
<% end %>

app/views/quizzes/create.js.erb
$('#response-form-container').empty().append("<%= j render 'questions/form' %>")

app/views/quizzes/edit.html.erb
<h1>Editing Quiz</h1>

<%= render 'form', quiz: @quiz %>

<%= link_to 'Show', @quiz %> |
<%= link_to 'Back', quizzes_path %>

app/views/quizzes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Quizzes</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @quizzes.each do |quiz| %>
      <tr>
        <td><%= link_to 'Show', quiz %></td>
        <td><%= link_to 'Edit', edit_quiz_path(quiz) %></td>
        <td><%= link_to 'Destroy', quiz, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= render 'quizzes/form' %>

app/views/quizzes/new.html.erb
<h1>New Quiz</h1>

<%= render 'form', quiz: @quiz %>

<%= link_to 'Back', quizzes_path %>

app/views/quizzes/quiz.html.erb
<%# <div id='quiz-page'>
  <p id="notice"><%= notice %></p> %>
<div id="question-container" class="container card bg-light">
  <%= render 'questions/form' %>
</div>
<%# </div> %>

app/views/quizzes/show.html.erb
<p id="notice"><%= notice %></p>
This is the quiz