config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  post 'login'  => 'placeholder#login',   :as => 'login'
  get  'login'  => 'placeholder#landing', :as => 'landing'
  get 'generate_orgs' => 'placeholder#generate_orgs', :as => 'finish_quiz'

  match '/auth/:provider/callback', to: "sessions#create", via: [:get, :post]
  get 'signin' => "sessions#signin", :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get 'auth/failure' => 'sessions#failure'

  root 'placeholder#home'
  resources :quizzes
  resources :response
  get 'quiz', to: 'quizzes#quiz', as: :take_quiz

  get 'profile/:id'=> 'profile#show', :as => 'show_profile'
  get 'profile/:id/edit' => 'profile#edit', :as => 'edit_profile'
  post 'profile/:id' => 'profile#update', :as => 'update_profile'
  
  get 'interests' => 'interests#index', :as => 'interests'
  post 'interests/upload' => 'interests#upload', :as => 'upload_interests'
end

app/controllers/placeholder_controller.rb
class PlaceholderController < ApplicationController
  
  public
  
  def landing
    if session[:logged_in]
      redirect_to root_path
    end
  end
  
  def login
    session[:logged_in] = true
    redirect_to root_path
  end
  
  def home
    if not session[:logged_in]
      redirect_to landing_path
    end
	@id = session[:user_id]
    @showAllOrgs = true
  end

  def generate_orgs
    quiz_results = Quiz.find(params[:quiz_id]).get_content
    #here are the interests and categories needed for the API call
    #i.e to get interests: quiz_results[:interests]
    
    @organizations = Organization.get_organizations(12, quiz_results[:categories], quiz_results[:interests])
    @showAllOrgs = false
    respond_to do |format|
      if @organizations.nil?
        format.js { flash[:alert] = 'There was a problem matching with organizations.' }
      else
        format.js
        format.html
      end
    end
  end
end

app/views/placeholder/_orgs.html.erb
<h3 class="matched"> <%= @showAllOrgs ? 'Take the quiz to get matched with orgs!' : 'Your matched organizations' %> </h3>
<div>
<% if @organizations%>
  <% @organizations.each_with_index do |org, i| %>
  <!-- Modal -->
    <div class="modal fade" id="<%= 'modal-' + i.to_s %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h3 class="modal-title text-center w-100"><%= org.name %></h3>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <div class="text-center"> 
              <%= image_tag(org.imageUrl) %>
            </div>
            <div>
              <h4>Description</h4>
              <%= raw org.description %>
            </div>
            <div> 
              <h4>Contact Information</h4>
              <% if not org.phone_number.blank?%>
                <i class="fa fa-phone fa-2x"></i> <%= org.phone_number %>
                <br>
              <% end %>
              <% if not org.email.blank?%>
                <i class="fa fa-envelope fa-2x"></i> <%= org.email %>
              <% end %>
              <div> 
                <% if not org.facebook.blank?%>
                  <a href="<%= org.facebook %>" target="_blank"><i class="fa fa-facebook-square fa-2x"></i></a>
                <% end %>
                <% if not org.twitter.blank?%>
                  <a href="<%= org.twitter %>" target="_blank"><i class="fa fa-twitter-square fa-2x"></i></a>
                <% end %>
                <% if not org.website.blank?%>
                  <a href="<%= org.website.include?('http') ? org.website : 'http://' + org.website %>" target="_blank"><i class="fa fa-globe fa-2x"></i></a>
                <% end %>
              </div>
            </div>
            <br>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  </div>
  <div class='container'>
    <div class='orgs'>
      <% @organizations.each_with_index do |org, i| %>
        <div class="snip1104 blue">
          <%= image_tag(org.imageUrl) %>
          <figcaption>
            <h4><%= org.name %></h2>
          </figcaption>
          <div class='fig-holder'>
            <button type="button" class="btn btn-outline-light" data-toggle="modal" data-target="#<%= 'modal-' + i.to_s %>">Learn More</button>
          </div>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/placeholder/generate_orgs.html.erb
<nav class="navbar navbar-expand-sm navbar-dark"">
  <div class="container">
     
  <a class="navbar-brand" href="/">communities<b>@Cal</b></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="collapsibleNavbar">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>    
    </ul>
  </div>  
  </div>
</nav>
<% if alert %>
  <!-- Alert if problem saving response. -->
  <p class="alert alert-warning alert-dismissible fade show">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </p>
<% end %>
<% if @showQuizWarning %>
<div id='home-hero' class="jumbotron text-center" style="background-color: #FF000">
  <h3 class='home-title'>FIND YOUR COMMUNITY AT CAL.<br/>GET MATCHED WITH ORGANIZATIONS NOW.</h3>
  <%= render 'quizzes/form' %>
</div>
<% end %>
<%= render "placeholder/orgs" %>

app/views/placeholder/generate_orgs.js.erb
$('#start-quiz-btn').prop('value', 'Retake Quiz');
$('#matched-orgs').fadeOut(500, function() {
    $('#matched-orgs').empty();
    $("<%= j render 'placeholder/orgs' %>").appendTo('#matched-orgs');
    $('.orgs').slick({
      dots: true,
      infinite: false,
      speed: 300,
      slidesToShow: 3,
      slidesToScroll: 3,
      responsive: [
        {
          breakpoint: 1024,
          settings: {
            slidesToShow: 3,
            slidesToScroll: 3,
            infinite: true,
            dots: true
          }
        },
        {
          breakpoint: 600,
          settings: {
            slidesToShow: 2,
            slidesToScroll: 2
          }
        },
        {
          breakpoint: 480,
          settings: {
            slidesToShow: 1,
            slidesToScroll: 1
          }
        }
      ]
    });
    $('#matched-orgs').fadeIn(1000);
  }
);

app/views/placeholder/home.html.erb
<nav class="navbar navbar-expand-sm navbar-dark">
  <div class="container">
     
  <a class="navbar-brand" href="/">communities<b>@Cal</b></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="collapsibleNavbar">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="<%= signout_path %>" >Sign Out</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= show_profile_path(@id) %>" >Profile</a>
      </li>
    </ul>
  </div>  
  </div>
</nav>

<div id='home-hero' class="jumbotron text-center" style="background-color: #FF000">
  <h3 class='home-title'>FIND YOUR COMMUNITY AT CAL.<br/>GET MATCHED WITH ORGANIZATIONS NOW.</h3>
  <%= render 'quizzes/form' %>
</div>
<div id='matched-orgs'>
  <%= render "placeholder/orgs" %>
</div>

app/views/placeholder/landing.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link href='https://fonts.googleapis.com/css?family=Roboto Slab' rel='stylesheet'>
    <style>
    html, body {
      background-image: url('<%= asset_path('prisms.png') %>'); 
      font-family: 'Roboto Slab';
      height:100%; /* important to vertically align the container */
      margin:0;
      padding:0;
    }
    .vertical-center {
      min-height: 100%;  /* Fallback for browsers do NOT support vh unit */
      min-height: 100vh; /* These two lines are counted as one 🙂       */
      display: flex;
      align-items: center;
    }
    </style>
    <title>Communities@Cal</title>
  </head>
  <body>

<div class="vertical-center" >
  <div class="container rounded" style="background-color: #FFFFFF; max-width:1000px" >
    <div class="row">
      <div class="col-sm-12" style="text-align:center">
          <%=image_tag("LEAD logo.png", :align=> "middle", :style => "width:300px")%>
          <h1>Communities@Cal</h1>
          <p>Please login through CalNet to continue.</p> 
          <%= form_tag signin_path, :method => 'get' do %>
          <div class="col-md-4 offset-md-4">
            <input id="login-button" type="submit" value="Sign in" class="btn btn-primary btn-block"
                   style="background: linear-gradient(#2683bc, #1f7099), #1f7099"/>
          </div>
          <% end %>
          <br>
      </div>
    </div>
  </div>
</div>



    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>